version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3

jobs:
  setup:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .
  lint:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Lint
          command: npm run lint
  test:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run test
  publish:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - setup
      - lint:
          context: 6rs-public-npm
          requires:
            - setup
      - test:
          context: 6rs-public-npm
          requires:
            - setup
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - lint
            - test
          filters:
            branches:
              only: fix/allow-array-types
