version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@3

jobs:
  setup:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .
  lint:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: check format
          command: npm run format:check
      - run:
          name: Lint
          command: npm run eslint:check -- --format junit --output-file ./reports/eslint/results.xml
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  test:
    docker:
      - image: cimg/node:14.17.6
    environment:
      MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run only:test
      - run:
          name: Coverage
          command: npm run only:lCov
      - sixrs-gke/codecov
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    docker:
      - image: cimg/node:14.17.6
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - setup
          context: 6rs-public-npm
          requires:
            - setup
      - lint:
          context: 6rs-public-npm
          requires:
            - setup
      - test:
          context: 6rs-public-npm
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - lint
            - test
          filters:
            branches:
              only: fix/allow-array-types
